# 应用配置
app:
  name: "light-stack"
  mode: "development" # development, production
  time_zone: "Asia/Shanghai"

# 服务器配置
server:
  port: "8080"

# 数据库配置
database:
  host: "matuto_db"
  port: "3306"
  username: "light_stack"
  password: "mzGdmZ85CZ2N5Ecm"
  database: "light_stack"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600

# Redis配置
redis:
  host: "matuto_db"
  port: "6379"
  password: "db_pass"
  db: 0
  pool_size: 10
  min_idle_conns: 5

# JWT配置
jwt:
  secret: "your-jwt-secret-key-change-in-production"
  expires_in: 86400 # 24小时

# 日志配置
log:
  level: "info"     # debug, info, warn, error
  format: "json"    # json, text
  output: "stdout"  # stdout, file

# 文件存储配置
file:
  local_path: "uploads"           # 本地存储路径
  base_url: "/api/static"         # 文件访问基础URL
  max_file_size: 52428800         # 默认最大文件大小 50MB (字节)